# Generated by Django 4.1.5 on 2023-05-05 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=250, unique=True)),
                ('link', models.TextField()),
                ('slug', models.SlugField(max_length=250, unique=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Branches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branchName', models.TextField(max_length=250, unique=True)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('Tdistrict', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeApp.district')),
            ],
            options={
                'ordering': ('branchName',),
            },
        ),
    ]
