# Generated by Django 4.1.5 on 2023-05-06 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('homeApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=250)),
                ('DOB', models.DateField()),
                ('age', models.IntegerField()),
                ('gender', models.TextField(max_length=15)),
                ('phone', models.IntegerField()),
                ('email', models.TextField()),
                ('address', models.TextField()),
                ('acType', models.TextField(max_length=250)),
                ('cc', models.BooleanField()),
                ('db', models.BooleanField()),
                ('cb', models.BooleanField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeApp.branches')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeApp.district')),
            ],
        ),
    ]
