# Generated by Django 4.1.5 on 2023-05-06 06:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0002_alter_account_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='acType',
        ),
        migrations.AddField(
            model_name='account',
            name='account',
            field=models.CharField(choices=[('S', 'Savings'), ('C', 'Current')], default=django.utils.timezone.now, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='address',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
